import type { Metadata } from "next";
import "../globals.css"
import Link from "next/link";
import { CookieBanner } from "@/components/CookieBanner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className="antialiased text-gray-900">
        <div className="min-h-screen flex flex-col">
          <header className="border-b bg-white">
            <div className="max-w-5xl mx-auto px-4 py-3 flex justify-between items-center">
              <Link href="/" className="font-semibold">
                Sans-papiers — MVP
              </Link>
              <nav className="flex items-center gap-3 text-sm">
                <Link href="/fr" className="hover:underline">
                  Accueil
                </Link>
                <Link href="/fr/legal" className="hover:underline">
                  Mentions légales
                </Link>
                <Link href="/fr/privacy" className="hover:underline">
                  RGPD
                </Link>
              </nav>
            </div>
          </header>

          <main className="flex-1">{children}</main>

          <footer className="border-t bg-white">
            <div className="max-w-5xl mx-auto px-4 py-6 text-xs text-gray-500 flex flex-wrap gap-3 justify-between">
              <div>© {new Date().getFullYear()} — Ceci n’est pas un conseil juridique.</div>
              <div className="flex gap-3">
                <Link href="/fr/legal" className="hover:underline">
                  Mentions légales
                </Link>
                <Link href="/fr/privacy" className="hover:underline">
                  Politique de confidentialité
                </Link>
              </div>
            </div>
          </footer>
        </div>

        <CookieBanner locale="fr" />
      </body>
    </html>
  );
}


